apiVersion: v1
kind: Secret
metadata:
  name: db2-credentials
type: Opaque
stringData:
  username: lfd89111
  password: ****
  host: 19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
  port: "30699"