apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-application-sa

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-application
  annotations:
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target: "1"
    spec:
      serviceAccountName: demo-application-sa
      containers:
        - name: flask
          image: quay.io/ntlawrence/demo-application@sha256:837b7d11236c8b5cc0af2491e3c95c35461cefd0b71c3f10f94feed1d9ddf345
          imagePullPolicy: IfNotPresent
          securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 100Mi
          ports:
            - containerPort: 5000
              name: http1
              protocol: TCP
          readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /alive
                port: 5000
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
          env: 
          - name: PG_HOST
            value: postgresql
          - name: PG_DB_NAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: postgresql
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: postgresql
          - name: PG_PWD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: postgresql
          - name: PG_PORT
            value: "5432"
          - name: COLUMN_INFO
            valueFrom:
              configMapKeyRef:
                key: columns
                name: credit-risk-columns
          - name: PREDICT_URL
            value: "http://credit-risk.ntl-us-ibm-com.svc.cluster.local/v1/models/credit-risk:predict"
          - name: EXPLAIN_URL
            value: "http://credit-risk.ntl-us-ibm-com.svc.cluster.local/v1/models/credit-risk:explain"