apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "credit-risk"
  annotations:
      sidecar.istio.io/inject: "false"
spec:
  predictor:
      maxReplicas: 4
      minReplicas: 1
      scaleTarget: 1
      scaleMetric: "concurrency"
      containers:
      - name: kserve-container
        image: "quay.io/ntlawrence/explain-demo@sha256:aaf247201ef04f14332756a87f54b2419a2374732bc82d69030abcbd76699974"
        args:
        - --grpc_port=8081
        command:
        - python
        - /code/inference_service.py
        env:
        - name: STORAGE_URI
          value: "s3://ntl-us-ibm-com/tar"
        - name: THRESHOLD
          value: "0.558"
        volumeMounts:
        - name: code
          mountPath: /code
          readOnly: true
        ports:
        - containerPort: 8081
          name: h2c
          protocol: TCP
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: fraud-1-datavol-1
          readOnly: true
      serviceAccountName: kserve-inference-sa
  transformer:
      maxReplicas: 4
      minReplicas: 1
      scaleTarget: 1
      scaleMetric: "concurrency"
      containers:
      - args:
        - --protocol=grpc-v2
        command:
        - python
        - /code/transformer_service.py
        env:
         - name: STORAGE_URI
           value: "s3://ntl-us-ibm-com/tar"
         - name: THRESHOLD
           value: "0.558"
        image: "quay.io/ntlawrence/explain-demo@sha256:aaf247201ef04f14332756a87f54b2419a2374732bc82d69030abcbd76699974"
        name: kserve-container
        volumeMounts:
          - name: code
            mountPath: /code
            readOnly: true
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      volumes:
        - name: code
          persistentVolumeClaim:
              claimName: fraud-1-datavol-1
              readOnly: true
      serviceAccountName: kserve-inference-sa
  explainer:
      minReplicas: 1
      scaleTarget: 1
      scaleMetric: "concurrency"
      containers:
      - name: kserve-container
        image: "quay.io/ntlawrence/explain-demo@sha256:aaf247201ef04f14332756a87f54b2419a2374732bc82d69030abcbd76699974"
        args:
        - --protocol=grpc-v2
        command:
        - python
        - /code/explainer.py
        env:
        - name: STORAGE_URI
          value: "s3://ntl-us-ibm-com/tar"
        volumeMounts:
        - name: code
          mountPath: /code
          readOnly: true
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: fraud-1-datavol-1
          readOnly: true
      serviceAccountName: kserve-inference-sa